# JavaScriptアプリケーションのビルドワークフロー
name: Simple Build

# stgブランチへのプッシュ時に実行
on:
  push:
    branches:
      - stg

jobs:
  build:
    # Ubuntu最新版で実行
    runs-on: ubuntu-latest
    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js v18をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 依存関係をクリーンインストール
      - name: Install dependencies
        run: npm ci

      # Lintを実行
      - name: Run linting
        run: npm run lint

      # JavaScriptのビルドを実行
      - name: Build JavaScript
        run: npm run build

      # ビルド成果物をアーティファクトとして保存
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist  # アーティファクト名
          path: dist/ # 保存するディレクトリパス
